language: python
python:
  - 3.5
services:
  - docker
install:
  - docker-compose up -d
script:
  - docker ps | grep -q nginx
  - docker ps | grep -q web
  - docker ps | grep -q db
  - curl -v --silent http://localhost 2>&1 | grep 'Public Salaries'
