# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0002_auto_20161127_2234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wage',
            unique_together=set([('first_name', 'last_name', 'middle_name', 'agency', 'dept', 'title', 'year')]),
        ),
    ]
