# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wages', '0003_auto_20161128_0239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='Government',
        ),
        migrations.RenameField(
            model_name='wage',
            old_name='agency',
            new_name='government',
        ),
        migrations.AlterUniqueTogether(
            name='wage',
            unique_together=set([('first_name', 'last_name', 'middle_name', 'government', 'dept', 'title', 'year')]),
        ),
    ]
